/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2017-2018 Fraunhofer IOSB (Author: Andreas Ebner)
 */

#ifndef UA_SERVER_PUBSUB_H
#define UA_SERVER_PUBSUB_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ua_server.h"

//forward declarations
struct UA_WriterGroupConfig;
typedef struct UA_WriterGroupConfig UA_WriterGroupConfig;
struct UA_DataSetFieldConfig;
typedef struct UA_DataSetFieldConfig UA_DataSetFieldConfig;

/**
 * .. _pubsub:
 *
 * Publish/Subscribe
 * =================
 *
 * Work in progress!
 * This part will be a new chapter later.
 *
 * TODO: write general PubSub introduction
 *
 * The Publish/Subscribe (PubSub) extension for OPC UA enables fast and efficient
 * 1:m communication. The PubSub extension is protocol agnostic and can be used
 * with broker based protocols like MQTT and AMQP or brokerless implementations like UDP-Multicasting.
 *
 * The PubSub API uses the following scheme:
 *
 * 1. Create a configuration for the needed PubSub element.
 *
 * 2. Call the add[element] function and pass in the configuration.
 *
 * 3. The add[element] function returns the unique nodeId of the internally created element.
 *
 * Take a look on the PubSub Tutorials for mor details about the API usage.::
 *
 *  +-----------+
 *  | UA_Server |
 *  +-----------+
 *   |    |
 *   |    |
 *   |    |
 *   |    |  +----------------------+
 *   |    +--> UA_PubSubConnection  |  UA_Server_addPubSubConnection
 *   |       +----------------------+
 *   |        |    |
 *   |        |    |    +----------------+
 *   |        |    +----> UA_WriterGroup |  UA_PubSubConnection_addWriterGroup
 *   |        |         +----------------+
 *   |        |              |
 *   |        |              |    +------------------+
 *   |        |              +----> UA_DataSetWriter |  UA_WriterGroup_addDataSetWriter  +-+
 *   |        |                   +------------------+                                     |
 *   |        |                                                                            |
 *   |        |         +----------------+                                                 | r
 *   |        +---------> UA_ReaderGroup |                                                 | e
 *   |                  +----------------+                                                 | f
 *   |                                                                                     |
 *   |       +---------------------------+                                                 |
 *   +-------> UA_PubSubPublishedDataSet |  UA_Server_addPublishedDataSet                <-+
 *           +---------------------------+
 *                 |
 *                 |    +-----------------+
 *                 +----> UA_DataSetField |  UA_PublishedDataSet_addDataSetField
 *                      +-----------------+
 *
 * Connections
 * -----------
 * The PubSub connections are the abstraction between the concrete transport protocol
 * and the PubSub functionality. It is possible to create multiple connections with
 * different transport protocols at runtime.
 *
 * Take a look on the PubSub Tutorials for mor details about the API usage.
 * Connections
 * -----------
 */

typedef struct{
    UA_String name;
    UA_Boolean enabled;
    union{ //std: valid types UInt or String
        UA_UInt32 numeric;
        UA_String string;
    }publisherId;
    UA_String transportProfileUri;
    UA_Variant address;
    size_t connectionPropertiesSize;
    UA_KeyValuePair *connectionProperties;
    UA_Variant connectionTransportSettings;
} UA_PubSubConnectionConfig;

/**
 * Connection handling
 * ^^^^^^^^^^^^^^^^^^^^
 */

UA_StatusCode
UA_Server_addPubSubConnection(UA_Server *server, const UA_PubSubConnectionConfig *connectionConfig,
                              UA_NodeId *connectionIdentifier);

UA_StatusCode
UA_Server_removePubSubConnection(UA_Server *server, UA_NodeId connectionIdentifier);

UA_StatusCode
UA_PubSubConnection_getConfig(UA_Server *server, UA_NodeId connectionIdentifier,
                              UA_PubSubConnectionConfig *config);
UA_StatusCode
UA_PubSubConnection_addWriterGroup(UA_Server *server, UA_NodeId connectionIdentifier,
                                   const UA_WriterGroupConfig *writerGroupConfig,
                                   UA_NodeId *writerGroupIdentifier);
UA_StatusCode
UA_PubSubConnection_removeGroup(UA_Server *server, UA_NodeId groupIdentifier);

/**
 * PublishedDataSets
 * -----------------
 * The PublishedDataSets (PDS) are containers for the published information. The PDS contain
 * the published variables and meta informations. The metadata is commonly autogenerated
 * or given as constant argument as part of the template functions. The template functions are standard
 * defined and intended for configuration tools. You should normally
 * create a empty PDS and call the functions to add new fields.
 */

typedef struct {
    UA_StatusCode addResult;
    size_t fieldAddResultsSize;
    UA_StatusCode *fieldAddResults;
    UA_ConfigurationVersionDataType configurationVersion;
} UA_AddPublishedDataSetResult;

typedef struct {
    UA_StatusCode result;
    UA_ConfigurationVersionDataType configurationVersion;
} UA_DataSetFieldResult;

typedef enum {
    UA_PUBSUB_DATASET_PUBLISHEDITEMS,
    UA_PUBSUB_DATASET_PUBLISHEDEVENTS,
    UA_PUBSUB_DATASET_PUBLISHEDITEMS_TEMPLATE,
    UA_PUBSUB_DATASET_PUBLISHEDEVENTS_TEMPLATE,
} UA_PublishedDataSetType;

/* The UA_PUBSUB_DATASET_PUBLISHEDITEMS has currently no additional members
 * and thus no dedicated config structure.
 */

typedef struct {
    UA_DataSetMetaDataType metaData;
    size_t variablesToAddSize;
    UA_PublishedVariableDataType *variablesToAdd;
} UA_PublishedDataItemsTemplateConfig;

typedef struct {
    UA_NodeId eventNotfier;
    UA_ContentFilter filter;
} UA_PublishedEventConfig;

typedef struct {
    UA_DataSetMetaDataType metaData;
    UA_NodeId eventNotfier;
    size_t selectedFieldsSize;
    UA_SimpleAttributeOperand *selectedFields;
    UA_ContentFilter filter;
} UA_PublishedEventTemplateConfig;

/* Configuration structure for PublishedDataSet */
typedef struct {
    UA_String name;
    UA_PublishedDataSetType publishedDataSetType;
    union{
        /* The UA_PUBSUB_DATASET_PUBLISHEDITEMS has currently no additional members
         * and thus no dedicated config structure.*/
        UA_PublishedDataItemsTemplateConfig itemsTemplate;
        UA_PublishedEventConfig event;
        UA_PublishedEventTemplateConfig eventTemplate;
    } config;
} UA_PublishedDataSetConfig;

/**
 * PublishedDataSet handling
 * ^^^^^^^^^^^^^^^^^^^^^^^^^^
 */

UA_AddPublishedDataSetResult
UA_Server_addPublishedDataSet(UA_Server *server, const UA_PublishedDataSetConfig *publishedDataSetConfig,
                              UA_NodeId *pdsIdentifier);

UA_StatusCode
UA_Server_removePublishedDataSet(UA_Server *server, UA_NodeId pdsIdentifier);

UA_StatusCode
UA_PublishedDataSet_getConfig(UA_Server *server, UA_NodeId publishedDataSetIdentifier,
                              UA_PublishedDataSetConfig *config);
void
UA_PublishedDataSetConfig_deleteMembers(UA_PublishedDataSetConfig *pdsConfig);

UA_DataSetFieldResult
UA_PublishedDataSet_addDataSetField(UA_Server *server, UA_NodeId publishedDataSetIdentifier,
                                    const UA_DataSetFieldConfig *fieldConfig,
                                    UA_NodeId *fieldIdentifier);
UA_DataSetFieldResult
UA_PublishedDataSet_removeField(UA_Server *server, UA_NodeId fieldIdentifier);

/**
 *
 * DataSetFields
 * -------------
 *
 * The description of published variables is named DataSetField.
 * Each DataSetField contains the selection of one information model node.
 * The DataSetField has additional parameters for the publishing,
 * sampling and error handling process.
 */

typedef struct{
    UA_ConfigurationVersionDataType configurationVersion;
    UA_String fieldNameAlias;
    UA_Boolean promotedField;
    UA_PublishedVariableDataType publishParameters;
} UA_DataSetVariableConfig;

typedef enum {
    UA_PUBSUB_DATASETFIELD_VARIABLE,
    UA_PUBSUB_DATASETFIELD_EVENT
} UA_DataSetFieldType;

struct UA_DataSetFieldConfig {
    UA_DataSetFieldType dataSetFieldType;
    union {
        UA_DataSetVariableConfig variable;
        //events need other config later
    } field;
};

/**
 * DataSetField handling
 * ^^^^^^^^^^^^^^^^^^^^^^
 */

UA_StatusCode
UA_DataSetField_getConfig(UA_Server *server, UA_NodeId dataSetFieldIdentifier,
                          UA_DataSetFieldConfig *config);
void
UA_DataSetFieldConfig_deleteMembers(UA_DataSetFieldConfig *dataSetFieldConfig);

/**
 * .. _dsw:
 *
 * DataSetWriter
 * -------------
 *
 * The DataSetWriters are the glue between the WriterGroups and the
 * PublishedDataSets. The DataSetWriter contain configuration parameters
 * and flags which influence the creation of DataSet messages. These messages
 * are encapsulated inside the network message. The DataSetWriter must be linked
 * with an existing PublishedDataSet and be contained within a WriterGroup.
 *
 */

typedef struct {
    UA_String name;
    UA_UInt16 dataSetWriterId;
    UA_DataSetFieldContentMask dataSetFieldContentMask;
    UA_UInt32 keyFrameCount;
    UA_ExtensionObject messageSettings;
    UA_String dataSetName;
    size_t dataSetWriterPropertiesSize;
    UA_KeyValuePair *dataSetWriterProperties;
} UA_DataSetWriterConfig;

/**
 * DataSetWriter handling
 * ^^^^^^^^^^^^^^^^^^^^^^^
 */

UA_StatusCode
UA_DataSetWriter_getConfig(UA_Server *server, UA_NodeId dataSetWriterIdentifier,
                           UA_DataSetWriterConfig *config);
void
UA_DataSetWriterConfig_deleteMembers(UA_DataSetWriterConfig *pdsConfig);

/**
 *
 * WriterGroup
 * -----------
 *
 * All WriterGroups are created within a PubSubConnection and automatically deleted
 * if the connection is removed. The WriterGroup is primary used as container for
 * :ref:`dsw` and network message settings. The WriterGroup can be
 * imagined as producer of the network messages. The creation of network messages
 * is controlled by parameters like the publish interval, which is e.g.
 * contained in the WriterGroup.
 *
 */

typedef enum {
    UA_PUBSUB_ENCODING_BINARY,
    UA_PUBSUB_ENCODING_JSON,
    UA_PUBSUB_ENCODING_UADP
} UA_PubSubEncodingType;

struct UA_WriterGroupConfig{
    UA_String name;
    UA_Boolean enabled;
    UA_UInt16 writerGroupId;
    UA_Double publishingInterval;
    UA_Double keepAliveTime;
    UA_Byte priority;
    UA_MessageSecurityMode securityMode;
    UA_ExtensionObject transportSettings;
    UA_ExtensionObject messageSettings;
    size_t groupPropertiesSize;
    UA_KeyValuePair *groupProperties;
    UA_PubSubEncodingType encodingMimeType;
    //non std. config parameter. maximum count of embedded DataSetMessage in one NetworkMessage
    UA_UInt16 maxEncapsulatedDataSetMessageCount;
};

/**
 * WriterGroup handling
 * ^^^^^^^^^^^^^^^^^^^^^
 */

UA_StatusCode
UA_WriterGroup_addDataSetWriter(UA_Server *server, UA_NodeId writerGroupIdentifier,
                                UA_NodeId dataSetIdentifier,
                                const UA_DataSetWriterConfig *dataSetWriterConfig,
                                UA_NodeId *writerIdentifier);

UA_StatusCode
UA_WriterGroup_removeDataSetWriter(UA_Server *server, UA_NodeId writerIdentifier);

UA_StatusCode
UA_WriterGroup_getConfig(UA_Server *server, UA_NodeId writerGroupIdentifier,
                         UA_WriterGroupConfig *config);

void
UA_WriterGroupConfig_deleteMembers(UA_WriterGroupConfig *writerGroupConfig);


#ifdef __cplusplus
} // extern "C"
#endif

#endif /* UA_SERVER_PUBSUB_H */
